### PR TITLE
Jfarmer/new relic

### PR DESCRIPTION
**Pull request by jfarmer**
Added New Relic

### CODE REVIEW

**Comment by ghost** [comment]
Checking now.

**Review by ghost — CHANGES_REQUESTED** [review]
Did you add the New Relic package to the dependency list?

**Comment by jfarmer** [comment]
> e dep



> Did you add the New Relic package to the dependency list?

I added it to the `Gemfile`. Is there another dependency list I need to add it to?

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Looking good!

**Pull request merged**
